# Generated by Django 5.1.1 on 2026-09-25 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('roles', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('ref_id', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('cursor', models.JSONField(default=dict)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.CharField(max_length=128, unique=True)),
                ('purpose', models.CharField(max_length=32)),
                ('audience', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('on_date', models.DateField()),
                ('requested_codes', models.JSONField(default=list)),
                ('payload_fingerprint', models.CharField(max_length=128)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('decision', models.JSONField(null=True)),
                ('decided_at', models.DateTimeField(null=True)),
                ('manual_review_reason', models.CharField(blank=True, default='', max_length=256)),
                ('fingerprint_snapshot', models.JSONField(default=dict)),
                ('consent_snapshot', models.JSONField(default=dict)),
                ('manifest_version', models.CharField(blank=True, default='', max_length=128)),
                ('reuse_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='consent.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(db_index=True, max_length=64)),
                ('version', models.PositiveIntegerField()),
                ('narrator_code', models.CharField(max_length=64)),
                ('session_code', models.CharField(max_length=64)),
                ('purpose', models.CharField(max_length=32)),
                ('audience', models.JSONField(default=list)),
                ('region', models.JSONField(default=list)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('attribution', models.CharField(max_length=256)),
                ('evidence_summary', models.CharField(max_length=512)),
                ('status', models.CharField(default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('opened_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consents_confirmed', to='consent.actor')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consents_opened', to='consent.actor')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consents_submitted', to='consent.actor')),
                ('supersedes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseding', to='consent.consent')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=128)),
                ('content_version', models.PositiveIntegerField(default=1)),
                ('fingerprint', models.CharField(max_length=128)),
                ('kind', models.CharField(max_length=32)),
                ('narrator_code', models.CharField(max_length=64)),
                ('session_code', models.CharField(max_length=64)),
                ('recorded_date', models.DateField()),
                ('status', models.CharField(default='registered', max_length=20)),
                ('restriction_note', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials_confirmed', to='consent.actor')),
                ('covered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='covered_materials', to='consent.consent')),
                ('derived_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derivatives', to='consent.material')),
                ('source_consent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshot_materials', to='consent.consent')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials_submitted', to='consent.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_version', models.CharField(max_length=128)),
                ('file_credential', models.CharField(max_length=128, unique=True)),
                ('state', models.CharField(default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('stopped_at', models.DateTimeField(null=True)),
                ('consent_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='consent.consent')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='consent.accessrequest')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='consent.material')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='consent.consent')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_rows', to='consent.material')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='pending', max_length=16)),
                ('sent_at', models.DateTimeField(null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notices', to='consent.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.CharField(blank=True, default='', max_length=512)),
                ('notice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='consent.notice')),
            ],
        ),
        migrations.CreateModel(
            name='TakedownOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=32)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('down_at', models.DateTimeField(null=True)),
                ('notified_at', models.DateTimeField(null=True)),
                ('receipted_at', models.DateTimeField(null=True)),
                ('consent_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='takedown_orders', to='consent.consent')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='takedown_orders', to='consent.material')),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='consent.takedownorder'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=64)),
                ('target', models.CharField(blank=True, default='', max_length=128)),
                ('detail', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='consent.actor')),
            ],
            options={
                'indexes': [models.Index(fields=['action', 'target'], name='consent_aud_action_667cc1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['narrator_code', 'session_code', 'purpose'], name='consent_con_narrato_0ad486_idx'),
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['status', 'valid_until'], name='consent_con_status_81dc5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consent',
            unique_together={('chain_id', 'version')},
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['recorded_date'], name='consent_mat_recorde_fb56af_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['kind', 'status'], name='consent_mat_kind_350ad0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('code', 'content_version')},
        ),
        migrations.AlterUniqueTogether(
            name='consentscope',
            unique_together={('consent', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='notice',
            unique_together={('order', 'recipient')},
        ),
    ]
