# Generated by Django 5.1.1 on 2026-09-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentscope',
            name='state',
            field=models.CharField(default='submitted', max_length=16),
        ),
    ]
