# Generated by Django 5.1.1 on 2026-09-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0002_consentscope_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='is_narrow',
            field=models.BooleanField(default=False),
        ),
    ]
